# Generated by Django 5.0.4 on 2026-03-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('tigo_money', 'Tigo Money'), ('banco_union', 'Banco Unión'), ('qr', 'QR'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Presentado'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/')),
                ('customer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.reservation')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
