# Generated by Django 5.1 on 2026-03-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0005_inventory_almacen_product_barcode_and_more'),
        ('vendors', '0008_vendor_moneda_caja_promocion_ticketconfig_turnocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gasto',
                'unique_together': {('vendor', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje de descuento'), ('monto_fijo', 'Monto fijo de descuento')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usos_maximos', models.IntegerField(blank=True, null=True)),
                ('usos_actuales', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('aplica_live', models.BooleanField(default=True)),
                ('aplica_pos', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('anulado', 'Anulado')], default='activo', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.categoriagasto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR / Transferencia'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito'), ('mixto', 'Mixto'), ('otro', 'Otro')], max_length=20)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='payment_icons/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=20)),
                ('cliente_nombre', models.CharField(default='Genérico', max_length=100)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada'), ('credito', 'Venta a crédito')], default='completada', max_length=20)),
                ('es_credito', models.BooleanField(default=False)),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('fecha_vencimiento_credito', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='vendors.caja')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.cupon')),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.metodopago')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='vendors.sucursal')),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='vendors.turnocaja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pos', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Venta POS',
                'verbose_name_plural': 'Ventas POS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentaPOSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.ventapos')),
            ],
            options={
                'verbose_name': 'Ítem de Venta POS',
                'verbose_name_plural': 'Ítems de Venta POS',
            },
        ),
    ]
