# Generated by Django 5.0.4 on 2026-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_categoriagasto_cupon_gastooperativo_metodopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='icono',
            field=models.CharField(blank=True, default='payments', max_length=50),
        ),
    ]
