# Generated by Django 5.1 on 2026-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_pago_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapos',
            name='canal_venta',
            field=models.CharField(choices=[('TIENDA', 'Tienda física'), ('LIVE', 'Live streaming'), ('WEB', 'Tienda web'), ('DOMICILIO', 'Envío a domicilio'), ('INTERPROVINCIAL', 'Envío interprovincial'), ('NACIONAL', 'Envío nacional')], default='TIENDA', max_length=20),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='direccion_envio',
            field=models.TextField(blank=True, help_text='Dirección para canales de envío', null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje aplicado (ej: 10.00 = 10%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Porcentaje'), ('FIXED', 'Monto fijo')], default='FIXED', max_length=10, null=True),
        ),
    ]
