# Generated by Django 5.0.4 on 2026-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_ventapos_descuento_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventapos',
            name='status',
            field=models.CharField(
                choices=[
                    ('completada', 'Completada'),
                    ('anulada', 'Anulada'),
                    ('credito', 'Venta a crédito'),
                    ('devuelto', 'Devuelto'),
                    ('parcialmente_devuelto', 'Parcialmente devuelto'),
                ],
                default='completada',
                max_length=30,
            ),
        ),
    ]
