# Generated by Django 5.0.4 on 2026-05-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_devolucion_status_ventapos'),
        ('vendors', '0019_add_transferencia_almacen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('total', 'Total'), ('parcial', 'Parcial')], default='parcial', max_length=10)),
                ('tipo_resolucion', models.CharField(choices=[('cambio', 'Cambio de producto'), ('devolucion_dinero', 'Devolución de dinero')], max_length=20)),
                ('motivo', models.TextField(blank=True, default='', help_text='Motivo de la devolución')),
                ('monto_devuelto', models.DecimalField(decimal_places=2, default=0, help_text='Monto a devolver al cliente', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procesado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='vendors.vendor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='payments.ventapos')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.devolucion')),
                ('venta_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='payments.ventapositem')),
            ],
            options={
                'verbose_name': 'Ítem de Devolución',
                'verbose_name_plural': 'Ítems de Devolución',
            },
        ),
    ]
