# Generated by Django 5.1 on 2026-05-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_devolucion_metodo_pago_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='metodo_pago_devolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='payments.metodopago'),
        ),
    ]
