# Generated by Django 5.0.4 on 2026-03-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('live', 'En vivo'), ('ended', 'Finalizada')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Sesión en Vivo',
                'verbose_name_plural': 'Sesiones en Vivo',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
