# Generated by Django 5.1 on 2026-03-13 00:53

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    LiveSession = apps.get_model('livestreams', 'LiveSession')
    for session in LiveSession.objects.all():
        base_slug = slugify(session.title) or 'live'
        session.slug = f"{base_slug}-{str(uuid.uuid4())[:8]}"
        session.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0001_initial'),
    ]

    operations = [
        # Primero agregar el campo sin unique, con default vacío
        migrations.AddField(
            model_name='livesession',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, default=''),
            preserve_default=False,
        ),
        # Generar slugs únicos para registros existentes
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Ahora aplicar el constraint unique
        migrations.AlterField(
            model_name='livesession',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
