# Generated by Django 5.1 on 2026-03-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0002_livesession_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='payment_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='payment_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='livestreams/qr/'),
        ),
    ]
