# Generated by Django 5.1 on 2026-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0003_payment_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='allow_multiple_cart',
            field=models.BooleanField(default=False, help_text='Si está activo, los clientes pueden agregar varios productos al carrito. Si está inactivo, compran de a un producto a la vez.', verbose_name='Permitir carrito multi-producto'),
        ),
    ]
