# Generated by Django 5.1 on 2026-04-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreams', '0004_livesession_allow_multiple_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1, help_text='Canal de transmisión simultánea (1, 2, 3...)'),
        ),
    ]
