# Generated by Django 5.0.4 on 2026-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='accepted_payment_methods',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/qr/'),
        ),
    ]
