# Generated by Django 5.1 on 2026-03-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_moneda_caja_promocion_ticketconfig_turnocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito'), ('ticket_venta', 'Ticket Venta'), ('ticket_compra', 'Ticket Compra')], max_length=20)),
                ('serie', models.CharField(blank=True, default='001', max_length=10)),
                ('correlativo', models.PositiveIntegerField(default=1)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'unique_together': {('vendor', 'tipo')},
            },
        ),
    ]
