# Generated by Django 5.0.4 on 2026-03-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='perm_expenses',
            field=models.BooleanField(default=False, verbose_name='Gastos'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_pos',
            field=models.BooleanField(default=False, verbose_name='Punto de Venta (POS)'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_warehouse',
            field=models.BooleanField(default=False, verbose_name='Almacén/Kardex'),
        ),
    ]
