# Generated by Django 5.0.4 on 2026-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_add_movimiento_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='diferencia_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='efectivo_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
