# Generated by Django 5.1 on 2026-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_add_diferencia_cierre_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='inventory_method',
            field=models.CharField(choices=[('peps', 'PEPS (Primeros en entrar, primeros en salir)'), ('ueps', 'UEPS (Últimos en entrar, primeros en salir)'), ('promedio', 'Costo Promedio')], default='peps', max_length=10, verbose_name='Método de valoración de inventario'),
        ),
    ]
