# Generated by Django 5.1 on 2026-05-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_add_variant_to_kardex_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='perm_compras',
            field=models.BooleanField(default=False, verbose_name='Compras'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='estado_suscripcion',
            field=models.CharField(choices=[('prueba', 'Prueba gratuita'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido')], default='prueba', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_usuarios',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de miembros de equipo permitidos'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notas_admin',
            field=models.TextField(blank=True, default='', help_text='Notas internas del superadmin (no visibles para el vendor)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='plan',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual - Bs. 300'), ('trimestral', 'Trimestral - Bs. 810'), ('semestral', 'Semestral - Bs. 1.499')], default='mensual', max_length=20),
        ),
    ]
