# Generated by Django 5.1 on 2026-05-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_add_suscripcion_perm_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='perm_orders',
            field=models.BooleanField(default=True, help_text='Acceso a pedidos / reservas', verbose_name='Pedidos'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='perm_payments',
            field=models.BooleanField(default=False, help_text='Acceso a pagos y caja', verbose_name='Pagos'),
        ),
    ]
