# Generated by Django 5.0.4 on 2026-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_add_perm_orders_perm_payments_to_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='perm_warehouse',
            field=models.BooleanField(default=False, verbose_name='Almacén/Transferencias'),
        ),
    ]
