# Generated by Django 5.0.4 on 2026-05-09 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_channel_flags'),
        ('vendors', '0017_customrole_perm_warehouse_verbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto — en progreso'), ('cerrado', 'Cerrado — pendiente aprobación'), ('aprobado', 'Aprobado — ajustes aplicados'), ('cancelado', 'Cancelado')], default='abierto', max_length=20)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_fisicos', to='vendors.almacen')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_creados', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_fisicos', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConteoFisicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField(default=0, help_text='Stock en sistema al momento del conteo')),
                ('stock_fisico', models.IntegerField(default=0, help_text='Stock contado físicamente')),
                ('diferencia', models.IntegerField(default=0, help_text='stock_fisico - stock_sistema (calculado)')),
                ('notas', models.CharField(blank=True, default='', max_length=300)),
                ('contado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_contados', to=settings.AUTH_USER_MODEL)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendors.conteofisico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteo_items', to='products.product')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteo_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Ítem de Conteo',
                'verbose_name_plural': 'Ítems de Conteo',
                'unique_together': {('conteo', 'producto', 'variante')},
            },
        ),
    ]
