# Generated by Django 5.0.4 on 2026-05-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_channel_flags'),
        ('vendors', '0018_add_conteo_fisico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='vendors.almacen')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='vendors.almacen')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_completadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Transferencia de Almacén',
                'verbose_name_plural': 'Transferencias de Almacén',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaAlmacenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_items', to='products.product')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendors.transferenciaalmacen')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Ítem de Transferencia',
                'verbose_name_plural': 'Ítems de Transferencia',
            },
        ),
    ]
