# Generated by Django 5.0.4 on 2026-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_add_transferencia_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexmovimiento',
            name='motivo',
            field=models.CharField(choices=[('venta', 'Venta'), ('venta_live', 'Venta Live'), ('compra', 'Compra/Reposición'), ('ajuste_manual', 'Ajuste manual'), ('devolucion', 'Devolución (venta)'), ('devolucion_compra', 'Devolución a proveedor'), ('transferencia', 'Transferencia')], max_length=30),
        ),
    ]
