# Generated by Django 5.0.4 on 2026-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_devolucion_compra_and_kardex_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='perm_almacen',
            field=models.BooleanField(default=False, verbose_name='Almacén / Kardex'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_arqueos',
            field=models.BooleanField(default=False, verbose_name='Arqueos de caja'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_configuracion',
            field=models.BooleanField(default=False, verbose_name='Configuración'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_conteos',
            field=models.BooleanField(default=False, verbose_name='Conteo físico'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_conteos_control',
            field=models.BooleanField(default=False, verbose_name='Control de conteos'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_devoluciones',
            field=models.BooleanField(default=False, verbose_name='Devoluciones POS'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_ecommerce_orders',
            field=models.BooleanField(default=False, verbose_name='Pedidos Web'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_proveedores',
            field=models.BooleanField(default=False, verbose_name='Proveedores'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_transferencias',
            field=models.BooleanField(default=False, verbose_name='Transferencias'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='perm_ventas_pos',
            field=models.BooleanField(default=False, verbose_name='Ventas POS'),
        ),
    ]
