# Generated by Django 5.0.4 on 2026-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_customrole_granular_22_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='perm_manage_roles',
            field=models.BooleanField(
                default=False,
                help_text='Permite crear/editar roles y gestionar miembros del equipo',
                verbose_name='Administrar roles/equipo',
            ),
        ),
    ]
