# Generated by Django 5.0.4 on 2026-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_customrole_perm_manage_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='modo_simple',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Activo: vendedor usa flujo simplificado. '
                    'Sin compras, sin PEPS, sin almacenes múltiples. '
                    'Solo activar desde el admin con la acción correspondiente.'
                ),
            ),
        ),
    ]
