# Generated by Django 5.0.4 on 2026-06-27 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_add_modo_simple_to_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='precio_editable',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el precio del producto solo se actualiza al recibir órdenes de compra. El campo precio no aparece en el formulario de producto.', verbose_name='Precio editable desde panel'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='transfer_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje de descuento aplicado al precio web por pago con transferencia. 0 = sin segundo precio.', max_digits=5, verbose_name='Descuento por transferencia (%)'),
        ),
    ]
