# Generated by Django 5.1 on 2026-05-09 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial_compras'),
        ('vendors', '0016_add_perm_orders_perm_payments_to_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompraitem',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén destino de este ítem específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_items', to='vendors.almacen'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='costo_mercaderia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo base de la mercadería por unidad', max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='costo_unitario_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='costo_mercaderia + flete_unitario (calculado)', max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='flete_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de flete por unidad', max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de ganancia sobre costo unitario total', max_digits=6),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='precio_venta_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta calculado (costo * (1 + %ganancia/100))', max_digits=12),
        ),
    ]
