# Generated by Django 5.0.4 on 2026-05-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_ordencompra_factura_compra'),
        ('products', '0010_product_channel_flags'),
        ('vendors', '0020_devolucion_compra_and_kardex_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_ref', models.CharField(blank=True, default='', help_text='Nota de remisión, guía u otro documento del proveedor', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_compra', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Devolución a proveedor',
                'verbose_name_plural': 'Devoluciones a proveedor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_compra_items', to='vendors.almacen')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.devolucioncompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_compra_items', to='products.product')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_compra_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Ítem devolución a proveedor',
                'verbose_name_plural': 'Ítems devolución a proveedor',
            },
        ),
    ]
