# Generated by Django 5.1 on 2026-05-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_ordencompraitemdistribucion_precio_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
