# Generated by Django 5.0.4 on 2026-06-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompraitem',
            name='precio_venta_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se copia a Inventory.precio_venta al confirmar la orden', max_digits=12, verbose_name='Precio de venta sugerido al recibir'),
        ),
    ]
