# Generated by Django 5.1 on 2026-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='variant_detail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('shipped', 'Enviada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=20),
        ),
    ]
