# Generated by Django 5.1 on 2026-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reservation_variant_detail_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('shipped', 'Enviada'), ('recibido', 'Recibido'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('paid', 'Pagada')], default='pending', max_length=20),
        ),
    ]
