# Generated by Django 5.0.4 on 2026-03-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_reservation_status'),
        ('payments', '0003_icono_imagefield_to_charfield'),
        ('products', '0006_product_sell_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='payments.cupon'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='products.productvariant'),
        ),
    ]
