# Generated by Django 5.1 on 2026-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_variants_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de compra por unidad'),
        ),
    ]
