# Generated by Django 5.1 on 2026-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventory_purchase_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('color_hex', models.CharField(blank=True, help_text='Color en formato #RRGGBB para mostrar swatch', max_length=7)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stock_extra', models.IntegerField(default=0, help_text='Stock adicional específico de esta variante (0 = usa el stock del producto)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
            },
        ),
    ]
