# Generated by Django 5.0.4 on 2026-06-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_web_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si es null, usa Product.price como fallback', max_digits=10, null=True, verbose_name='Precio de venta del lote'),
        ),
    ]
